export const exampleImportJson = JSON.stringify({
  attractions: [
    {
      external_id: 'spot-lingshan-buddha',
      name: '灵山大佛',
      category: '文化地标',
      summary: '灵山胜境核心景点，适合祈福、文化讲解和拍照停留。',
      tags: ['佛教文化', '祈福', '地标'],
      visit_minutes: 45,
      difficulty: 2,
      indoor: false,
      popularity: 95,
      satisfaction: 4.8,
      enabled: true,
      review_status: '可导入',
    },
    {
      external_id: 'spot-nine-dragons',
      name: '九龙灌浴',
      category: '演艺景观',
      summary: '以佛教典故为主题的动态景观，适合安排在大佛前后游览。',
      tags: ['演艺', '佛教文化', '亲子'],
      visit_minutes: 25,
      difficulty: 1,
      indoor: false,
      popularity: 88,
      satisfaction: 4.6,
      enabled: true,
      review_status: '可导入',
    },
  ],
  templates: [
    {
      external_id: 'route-half-day-classic',
      name: '灵山经典半日线',
      summary: '串联核心文化点位，适合首次到访游客。',
      interest_tags: ['佛教文化', '祈福'],
      duration_minutes: 120,
      intensity: 'medium',
      enabled: true,
    },
  ],
  stops: [
    {
      template_external_id: 'route-half-day-classic',
      attraction_external_id: 'spot-lingshan-buddha',
      order_index: 1,
      stay_minutes: 45,
      note: '核心停留点，优先安排讲解。',
    },
    {
      template_external_id: 'route-half-day-classic',
      attraction_external_id: 'spot-nine-dragons',
      order_index: 2,
      stay_minutes: 25,
      note: '结合演出时间调整顺序。',
    },
  ],
  materials: [
    {
      attraction_external_id: 'spot-lingshan-buddha',
      interest_tag: '佛教文化',
      title: '灵山大佛讲解',
      focus: '建造背景、祈福文化与观景位置',
      script: '这里是灵山胜境的核心地标，可以从大佛高度、文化寓意和游客祈福体验三个角度讲解。',
      enabled: true,
    },
  ],
  edges: [
    {
      from_attraction_external_id: 'spot-lingshan-buddha',
      to_attraction_external_id: 'spot-nine-dragons',
      walk_minutes: 8,
      distance_meters: 450,
      difficulty: 1,
      bidirectional: true,
      enabled: true,
    },
  ],
  config: {
    weights: {
      interest_match: 0.45,
      satisfaction: 0.2,
      popularity: 0.15,
      time_fit: 0.1,
      intensity_fit: 0.1,
    },
  },
}, null, 2);
